//------------------------------------------------------------------------
// Copyright(c) 2026 Yonie.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFileName	"WetReverb.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"WetReverb VST3 (64Bit)"
#else
#define stringFileDescription	"WetReverb VST3"
#endif
#define stringCompanyName		"Yonie\0"
#define stringLegalCopyright	"Copyright(c) 2026 Yonie."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"